### ISSUE TITLE
Suggestion: Dye Color for Clothes

### ISSUE THREAD

**Issue by ColonelTractor** [Silverfeelin/Starbound-SpawnableItemPack#11]
I'm not an expert programmer, so I'm not entirely sure how complicated the coding would be, but I imagine it would be simple, and convienient, to spawn in seperate colors of clothing (again, this is someone with little coding experience, so sorry if I'm being dumb).

**Comment by Silverfeelin** [comment]
Sorry for the (very) late reply. I don't currently have any plans to add new controls for specific (sets of) items.

You might want to take a look at:
https://github.com/Silverfeelin/Starbound-Wardrobe

**Comment by ColonelTractor** [comment]
No problem with the lateness, but I've already been using that XD

**Comment by Silverfeelin** [comment]
This has been implemented in v1.3.2.
https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v.1.3.2.1
