### ISSUE TITLE
Adding items help.

### ISSUE THREAD

**Issue by coemgen98** [Silverfeelin/Starbound-SpawnableItemPack#12]
Hello! I would just like to inquire about the location of the project that allows Windows users to easily generate a JSON patch for items found in an asset folder? I would have liked to add some items in for my personal use but unfortunately I can't seem to find it. Thanks and have a great day.

**Comment by Silverfeelin** [comment]
The tool isn't included with releases, but can instead be found in the source code. You can download the source code from the below link, or through the download button as shown in the image. The folder you're looking for is `/SpawnableItemFetcher/build`.

https://github.com/Silverfeelin/Starbound-SpawnableItemPack/archive/master.zip

![](http://i.los.so/e/x151016-042422.png)

**Comment by coemgen98** [comment]
Oh! Thank you so much! Have a nice day!
