### ISSUE TITLE
Add Codex/Similar Items

### ISSUE THREAD

**Issue by ghost** [Silverfeelin/Starbound-SpawnableItemPack#13]
Add items that fit into a category that would include codex entries for different races, missions, etc found within the game to spawn using the item pack mod.

**Comment by Silverfeelin** [comment]
Sorry for the late reply.

Codices and recipes are generated by the game. Together with the codices being generated, other events might take place that your save game relies on.
I could take a look at how feasible it is to have an external tool generate the codices to the mod can read them from my own files, but I don't know when I'll be able to get to this.

**Comment by Silverfeelin** [comment]
Added codices and blueprints in https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v1.3.2.3.
