### ISSUE TITLE
Pixels And Ancient Essence - Mod compatibility

### ISSUE THREAD

**Issue by PineapplExplosive** [Silverfeelin/Starbound-SpawnableItemPack#16]
I would like if this option was available like giving pixels or essence directly, i know that you can spawn an ancient essence chest and it would give unlimited essence but it's slower, and for the pixels, there are the 5k voxels but again, it's slower. also mod compatibility, like fracking universe and those. i mean big mods like recognized ones

Regards.
-PE

**Comment by Silverfeelin** [comment]
I won't know when I have the time to implement the currencies, but it's definitely something I have been wanting to add.

For mod compatibilities, check the overview. I won't be making compatibility patches because I don't want to maintain them every time a mod gets changed.

**Comment by Silverfeelin** [comment]
Sorry, this has been implemented a while ago but I forgot to update this post! Currencies can be found under the last "Other" category (or search for pixel/essence).
