### ISSUE TITLE
Suggestion: Duplicator mode

### ISSUE THREAD

**Issue by Fevix** [Silverfeelin/Starbound-SpawnableItemPack#24]
Give it an item and it makes however many copies of that item you want. 

I'm not 100% sure if this is possible in a purely GUI/clientside sense, as the only place I've seen it has been in the Creative Mode with the duplicator objects (Press E on the duplicator object, get 1/10/100/1000 of the item you're holding, depending on which duplicator you're using.)

**Comment by Silverfeelin** [comment]
How about dragging the item in the item slot on the right, and then pressing Print like you would normally do to obtain copies?

Currently the biggest downside is that you can't deselect a list item, so the list has to be repopulated. If I don't do this, any previously selected item would remain "selected" in the list while the actual item shown on the right is the one you dropped on the item slot.

I won't be adding the specification options (clothing color, weapon element and such) to keep this simple both for the users and myself.

https://streamable.com/ht3rm

**Comment by Silverfeelin** [comment]
The proposed solution has been included in https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v1.3.2.2.
