### ISSUE TITLE
having a hard time getting modded items in SIP

### ISSUE THREAD

**Issue by smb64** [Silverfeelin/Starbound-SpawnableItemPack#25]
I was able to get the SIF to work and I got the json file, but I can't seem to get the items to appear in SIP. could you see what I may have done wrong?
[SIP-Penguin Piracy Addon.zip](https://github.com/Silverfeelin/Starbound-SpawnableItemPack/files/1236813/SIP-Penguin.Piracy.Addon.zip)

**Comment by Silverfeelin** [comment]
The patch file name should be `sipCustomItems.json.patch`. I will update the Wiki to make this clear.

Another thing to note is that your metadata file is incorrect. This may result in your mod loading before SIP, which would mean the items are still missing even after correcting the file name. Your metadata file should be named `_metadata` (no extension).

**Comment by Silverfeelin** [comment]
I've added the step to https://github.com/Silverfeelin/Starbound-SpawnableItemPack/wiki/Adding-Items#applying-the-patch.

If you have any further issues please let me know, otherwise feel free to close this issue.

**Comment by smb64** [comment]
I do have a suggestion. maybe the SIF should also create a metadata file that just has the 'includes' part and the mod's name from the path

**Comment by Silverfeelin** [comment]
The tool can also be used by modders to include a patch out of the box (in their actual mod). It doesn't make much sense to make the tool spit out a mod when some people only want a patch.

**Comment by Silverfeelin** [comment]
I've updated the Spawnable Item Fetcher tool. It now uses a GUI and patches (or creates) everything for a patch mod to work. If you're experiencing issues with that tool please re-open this issue.

https://github.com/Silverfeelin/Starbound-SpawnableItemPack/tree/master/sipMods
