### ISSUE TITLE
Weapon Level Selection

### ISSUE THREAD

**Issue by Silverfeelin** [Silverfeelin/Starbound-SpawnableItemPack#3]
Requested by jintoya and [SkullTraill](http://community.playstarbound.com/threads/spawnable-item-pack-spawn-all-items-for-free.57271/page-37#post-2972516).

A slider or another type of input that allows users to set the level used by generated weapons.
#### Requires:
- New UI elements.
- Override of the spawn item callback, to add the level parameter if the spawned item is a valid weapon.
#### Current workaround:

None inside of SIP. You can spawn an item with a different level using the following command:  
`/spawnitem itemName count '{"level":10}'`

**Comment by skulltraill** [comment]
Thank you for considering this!

**Comment by Silverfeelin** [comment]
Solved in commit [dac79992ad1615346a2e0c109c8eb75b2b86932f](https://github.com/Silverfeelin/SpawnableItemPack/commit/dac79992ad1615346a2e0c109c8eb75b2b86932f).
A new release is expected soon (v1.0.4).
- Enabled the settings menu.
- Added a level input to the settings menu.
  - This value only affects items that have a `level` parameter set in the original item configuration.
  - This value is clamped between 1 and 10.

The setting menu can be opened by clicking on the cog in the top right corner, next to the return and close buttons.

![Settings](https://raw.githubusercontent.com/Silverfeelin/SpawnableItemPack/master/readme/settings.png)
