### ISSUE TITLE
Update for v1.4.3

### ISSUE THREAD

**Issue by Archilyte** [Silverfeelin/Starbound-SpawnableItemPack#32]
So 1.4.2 adds some new flags refrencing "Wargrove"
I cant get those items from the menu...
Can you add those items to the list?

**Comment by Silverfeelin** [comment]
I will generate a new item list later today. Thanks.

**Comment by Silverfeelin** [comment]
My apologies, I've been too busy today. I will get to it this Friday.

**Comment by Archilyte** [comment]
Thank you

**Comment by Silverfeelin** [comment]
Released in https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/tag/v1.4.3.
