### ISSUE TITLE
kind of completely breaks the quickbar

### ISSUE THREAD

**Issue by connorhedgehog** [Silverfeelin/Starbound-SpawnableItemPack#36]
hey so, i decided to download this, thinking it'd be nice to not have to look up item ids. 
i already had the quickbar mini mod so i thought everything would be fine, but it was not.

when i got in game and clicked on the quickbar, it just opened the manipulator module upgrade screen and gave no sidebar, which is necessary for using this and a few other mods i have.

**Comment by Silverfeelin** [comment]
This mod can in no way replace the Quickbar back with the old matter manipulator panel. The Spawnable Item Pack just adds an icon to the Quickbar file, so at worst the interface wouldn't function but at least open **or** the Quickbar would work fine but not show this interface.
Are you sure you didn't install any other mods?

![image](https://user-images.githubusercontent.com/17196309/93109750-bafe5e00-f6b4-11ea-9cb6-1e3c38a52ef3.png)

**Comment by connorhedgehog** [comment]
> This mod can in no way replace the Quickbar back with the old matter manipulator panel. The Spawnable Item Pack just adds an icon to the Quickbar file, so at worst the interface wouldn't function but at least open **or** the Quickbar would work fine but not show this interface.
> Are you sure you didn't install any other mods?
> 
> ![image](https://user-images.githubusercontent.com/17196309/93109750-bafe5e00-f6b4-11ea-9cb6-1e3c38a52ef3.png)

i have only one other mod besides this one that isn't quickbar, and with it the quickbar worked fine. i tried removing that mod so it was only the cheat mod and quickbar (which would make it useless for my needs anyway) and it still brought up the maniuplator module upgrade screen.

**Comment by Silverfeelin** [comment]
So removing SpawnableItemPack.pak will make the Quickbar work once again, and placing back the pak will then again stop the Quickbar from showing?

Are you using these files?
https://github.com/Silverfeelin/Starbound-SpawnableItemPack/releases/download/v1.4.3/SpawnableItemPack.pak (v1.4.3)
https://github.com/Silverfeelin/Starbound-Quickbar-Mini/releases/download/v0.36.1/QuickbarMini.pak (v0.36.1)

**Comment by connorhedgehog** [comment]
i'm 99.9% sure i'm using the latest version of quickbar (i installed spawnable item pack directly from releases) but i'll try it

if it doesn't work, i'll come back with a screenshot to show what i mean

**Comment by connorhedgehog** [comment]
turns out the quickbar mini thing i was using is a version or two behind, i don't really go out of my way to check if a mod is outdated and it came with my other mod soo
thanks for the help
