### ISSUE TITLE
Unstable items

### ISSUE THREAD

**Issue by Suphax** [Silverfeelin/Starbound-SpawnableItemPack#6]
In the settings menu, could be an idea for a checkbox to enable/disable showing unstable items/ones that can bug out, like spawning shops or the 2-stop teleshop teleporter.

**Comment by Silverfeelin** [comment]
The problem is figuring out what items are "unstable". Some items (filled capture pods) were already removed from SIP because they should never be spawned directly into the game.

I recommend ignoring broken items, and reporting the item identifiers (itemName or objectName).
