### ISSUE TITLE
Mods items should be in the SIP window.

### ISSUE THREAD

**Issue by HeyShell** [Silverfeelin/Starbound-SpawnableItemPack#9]
The title says everything.

**Comment by Silverfeelin** [comment]
Read: https://github.com/Silverfeelin/SpawnableItemPack#adding-items
If you have any suggestions that would make this request possible, feel free to tell me!

**Comment by Silverfeelin** [comment]
Closed. Maybe we can revisit this when ChuckleFish adds a way for us to check what items the game knows of.
